# Generated by Django 2.0.3 on 2018-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('weightValue', models.IntegerField()),
                ('weightType', models.CharField(choices=[('mcg', 'ug'), ('gram', 'g'), ('kilogram', 'kg'), ('ton', 'short_ton'), ('metric tonne', 'tonne'), ('metric ton', 'tonne'), ('ounce', 'oz'), ('pound', 'lb'), ('pounds', 'lb'), ('lbs', 'lb'), ('pood', ''), ('short ton', 'short_ton'), ('long ton', 'long_ton')], default=1000.0, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='movement',
            name='category',
            field=models.CharField(choices=[('Gymnastics', 'Gymnastics'), ('Weight Lifting', 'Weight Lifting'), ('Monostructural', 'Monostrutural')], default=('Gymnastics', 'Gymnastics'), max_length=32),
        ),
    ]
