# Generated by Django 2.0.3 on 2018-10-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20181021_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='weightType',
            field=models.CharField(choices=[('ug', 'mcg'), ('lb', 'pound'), ('tonne', 'metric ton'), ('g', 'gram'), ('tonne', 'metric tonne'), ('kg', 'kilogram'), ('pood', 'pood'), ('long_ton', 'long ton'), ('oz', 'ounce'), ('lb', 'lbs'), ('short_ton', 'short ton'), ('short_ton', 'ton'), ('lb', 'pounds')], default='kg', max_length=32),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default='20181021', max_length=32, unique=True),
        ),
    ]
