# Generated by Django 2.0.3 on 2018-10-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Gymnastics', 'G'), ('Weight Lifting', 'W'), ('Monostrutural', 'M')], default='G', max_length=32)),
                ('distance_enable', models.BooleanField(default=False)),
                ('height_enable', models.BooleanField(default=False)),
                ('weight_enable', models.BooleanField(default=False)),
                ('reps_enable', models.BooleanField(default=False)),
                ('calorie_enable', models.BooleanField(default=False)),
                ('time_enable', models.BooleanField(default=False)),
            ],
        ),
    ]
