# Generated by Django 2.0.3 on 2018-10-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20181020_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='caloriesScalingFactor',
            field=models.FloatField(default=1.0, help_text="Some equipment doesn't have a 1-1 effort, there is usual the baseline, or standard equipment. Use this value to scale the effort to make it eqiuvalent to the standard equipment."),
        ),
        migrations.AddField(
            model_name='equipment',
            name='distanceScalingFactor',
            field=models.FloatField(default=1.0, help_text="Some equipment doesn't have a 1-1 effort, there is usual the baseline, or standard equipment. Use this value to scale the effort to make it eqiuvalent to the standard equipment."),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weightType',
            field=models.CharField(choices=[('long_ton', 'long ton'), ('ug', 'mcg'), ('lb', 'pound'), ('tonne', 'metric ton'), ('kg', 'kilogram'), ('tonne', 'metric tonne'), ('lb', 'lbs'), ('short_ton', 'ton'), ('pood', 'pood'), ('g', 'gram'), ('oz', 'ounce'), ('short_ton', 'short ton'), ('lb', 'pounds')], default=1000.0, max_length=32),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weightValue',
            field=models.FloatField(default=0.0),
        ),
    ]
