# Generated by Django 2.0.3 on 2018-10-22 02:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20181020_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='body_weight_ratio',
            field=models.FloatField(default=1.0, help_text="Some movements use a body weight, some movents don't and others are inbetween.", validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='movements',
            field=models.ManyToManyField(to='workout.Movement', verbose_name='list of movements'),
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='20183510/21/18', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='weightType',
            field=models.CharField(choices=[('short_ton', 'short ton'), ('long_ton', 'long ton'), ('lb', 'pound'), ('kg', 'kilogram'), ('short_ton', 'ton'), ('tonne', 'metric tonne'), ('g', 'gram'), ('pood', 'pood'), ('ug', 'mcg'), ('lb', 'lbs'), ('tonne', 'metric ton'), ('oz', 'ounce'), ('lb', 'pounds')], default='kg', max_length=32),
        ),
        migrations.AlterField(
            model_name='movement',
            name='category',
            field=models.CharField(choices=[('G', 'Gymnastics'), ('W', 'Weight Lifting'), ('M', 'Monostructural')], default=('G', 'Gymnastics'), max_length=32),
        ),
        migrations.AlterField(
            model_name='movement',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
